package main.clientServerConversation;

public enum ClientRequests {
    USER_AUTHENTICATION_REQUEST, USER_ACCOUNT_CREATION_REQUEST,
    USER_TASK_LOG_HANDLER_REQUEST,
    NEW_TASK_ADDITION_REQUEST, TASK_DELETE_REQUEST,
    END_OF_WORK
}
