package main.clientServerConversation;

public enum ServerRespond {
    USER_AUTHENTICATION_ANSWER, USER_ACCOUNT_CREATION_ANSWER,
    USER_TASK_LOG_HANDLER_ANSWER,
    NEW_TASK_ADDITION_ANSWER, TASK_DELETE_ANSWER,
    END_OF_WORK
}
